name: 🚀 Deploy website on push

on: 
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔍 Debug environment
        run: |
          echo "FTP Server: ${{ secrets.ftp_server }}"
          echo "FTP User: ${{ secrets.ftp_user }}"
          echo "Resolving FTP server address..."
          nslookup ${{ secrets.ftp_server }}

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: /home2/sofco219/rapidoguarulhos.com.br/
          protocol: ftps
          port: 990
